apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sProtectedNamespace
metadata:
  name: deny-protected-namespaces-deletion
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    annotations:
      protectedKey: "acme.devops/protected"
